export const FLIP_BODY = 'FLIP_BODY';
export const MUSCLE_SELECTED = 'MUSCLE_SELECTED';
export const MUSCLE_FORCE_CHANGED = 'MUSCLE_FORCE_CHANGED';
export const SAVE_PATIENT = "SAVE_PATIENT";
export const SET_TRAITMENT = "SET_TRAITMENT";
