export const FLIP_BODY = 'FLIP_BODY';
export const ELEMENT_SELECTED = 'ELEMENT_SELECTED';
export const REFLEX_CHANGED = 'REFLEX_CHANGED';
export const MUSCLE_FORCE_CHANGED = 'MUSCLE_FORCE_CHANGED';
export const SAVE_PATIENT = "SAVE_PATIENT";
export const SET_TRAITMENT = "SET_TRAITMENT";
